# Generated by Django 5.2.17 on 2026-09-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.CharField(max_length=30, unique=True)),
                ('last_name', models.CharField(max_length=120)),
                ('first_names', models.CharField(max_length=180)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('emergency_contact', models.CharField(blank=True, max_length=180)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('history', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('insurance', models.CharField(blank=True, max_length=180)),
                ('insurance_number', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_names'],
            },
        ),
    ]
